version: '3'
services:
  app:
    build: .
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mongodb://root:root_password@database:27017/readings?retryWrites=true&w=majority&authSource=admin
      GEMINI_API_KEY: ${GEMINI_API_KEY}
  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: readings